// src/components/api.js

export const fetchMockData = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        loanDetails: {
          bank: "Bank Of America",
          address: "Lighthouse Storage Batesville",
          initialLoanBalance: "$450,000",
          remainingLoanBalance: "$422,922",
          initialAmortization: "360 months",
          remainingAmortization: "347 months",
          initialTerm: "60 months",
          remainingTerm: "47 months",
          monthlyPayment: "$1,720",
        },
        interestDetails: {
          interestRate: "2.5%",
          interestOnlyPeriod: "12 months",
          rateType: "Fixed",
          principalPaydownStart: "12/05/2023",
          maturationDate: "12/05/2023",
        },
        chartData: {
          interest: "$1,254,011",
          principal: "$675,237",
        },
        debtSchedule: [
          {
            month: "01",
            date: "May 2021",
            monthlyPayment: "$3,312,000",
            interest: "$3,312,000",
            principalPayDown: "$3,312,000",
            endingPrincipal: "$449,124",
            cumulativeInterest: "$844",
          },
          {
            month: "02",
            date: "June 2021",
            monthlyPayment: "$3,312",
            interest: "$1,980",
            principalPayDown: "$1,332",
            endingPrincipal: "$447,356",
            cumulativeInterest: "$3,980",
          },
          {
            month: "03",
            date: "July 2021",
            monthlyPayment: "$3,312",
            interest: "$1,960",
            principalPayDown: "$1,352",
            endingPrincipal: "$446,004",
            cumulativeInterest: "$5,940",
          },
          {
            month: "04",
            date: "August 2021",
            monthlyPayment: "$3,312",
            interest: "$1,940",
            principalPayDown: "$1,372",
            endingPrincipal: "$444,632",
            cumulativeInterest: "$7,880",
          },
          {
            month: "05",
            date: "September 2021",
            monthlyPayment: "$3,312",
            interest: "$1,920",
            principalPayDown: "$1,392",
            endingPrincipal: "$443,240",
            cumulativeInterest: "$9,800",
          },
          {
            month: "06",
            date: "October 2021",
            monthlyPayment: "$3,312",
            interest: "$1,900",
            principalPayDown: "$1,412",
            endingPrincipal: "$441,828",
            cumulativeInterest: "$11,700",
          },
          {
            month: "07",
            date: "November 2021",
            monthlyPayment: "$3,312",
            interest: "$1,880",
            principalPayDown: "$1,432",
            endingPrincipal: "$440,396",
            cumulativeInterest: "$13,580",
          },
          {
            month: "08",
            date: "December 2021",
            monthlyPayment: "$3,312",
            interest: "$1,860",
            principalPayDown: "$1,452",
            endingPrincipal: "$438,944",
            cumulativeInterest: "$15,440",
          },
          {
            month: "09",
            date: "January 2022",
            monthlyPayment: "$3,312",
            interest: "$1,840",
            principalPayDown: "$1,472",
            endingPrincipal: "$437,472",
            cumulativeInterest: "$17,280",
          },
          {
            month: "10",
            date: "February 2022",
            monthlyPayment: "$3,312",
            interest: "$1,820",
            principalPayDown: "$1,492",
            endingPrincipal: "$435,980",
            cumulativeInterest: "$19,100",
          },
          {
            month: "11",
            date: "March 2022",
            monthlyPayment: "$3,312",
            interest: "$1,800",
            principalPayDown: "$1,512",
            endingPrincipal: "$434,468",
            cumulativeInterest: "$20,900",
          },
          {
            month: "12",
            date: "April 2022",
            monthlyPayment: "$3,312",
            interest: "$1,780",
            principalPayDown: "$1,532",
            endingPrincipal: "$432,936",
            cumulativeInterest: "$22,680",
          },
        ],
      });
    }, 1000);
  });
